[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.22" }
winapi = { version = "0.3", features = ["windef", "winuser", "combaseapi", "basetsd", "ntdef", "minwindef"] }
image = "0.24"
rayon = "1.5"